### ISSUE TITLE
 command() missing 1 required positional argument: 'command'

### ISSUE THREAD

**Issue by endemeshkin** [andrewsayre/pysmartthings#15]
I have a problem with the command execution (Samsung TV)

```
async def some_function():
  async with aiohttp.ClientSession() as session:
    api = pysmartthings.SmartThings(session, token)
    locations = await api.locations()
    print(len(locations))
    devices = await api.devices()
    print(len(devices))
    device = devices[0]
    print(device.device_id)
    print(device.name)
    print(device.label)
    print(device.capabilities)

    print ("status --->>")
    await device.status.refresh()
    print(device.status.values)
    print(device.status.switch)
    result = await device.command("switch", "on")
    assert result == True

asyncio.get_event_loop().run_until_complete(some_function())
```
Out:

```
[TV] Samsung 7 Series (49)
Samsung 7 Series (49)
['switch', 'refresh', 'ocf', 'audioVolume', 'execute', 'tvChannel', 'mediaInputSource']
True
Traceback (most recent call last):
  File "smartth.py", line 43, in <module>
    asyncio.get_event_loop().run_until_complete(some_function())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "smartth.py", line 40, in some_function
    result = await device.command("switch", "on")
TypeError: command() missing 1 required positional argument: 'command'
```

What argument is required? The shutdown\shutdown command is standard for all devices

**Comment by andrewsayre** [comment]
There are three required parameters for ‘command’:  ‘async def command(self, component_id: str, capability, command, args=None) -> bool:’

You need to specify ‘capability_id’ as the first param.

Also know that there are convenience methods for most well known commands.  For switch it’s ‘switch_on’ and ‘switch_off’

**Comment by andrewsayre** [comment]
Will close this for now -- let me know if you're still having issues.

**Comment by teoavv94** [comment]
Hi @andrewsayre Were can I found the component_id? Can you explain me with an example if you can? Thank you!
