### ISSUE TITLE
Add IR_OCF Device type

### ISSUE THREAD

**Issue by acras9** [andrewsayre/pysmartthings#16]
Recently, Samsung is beta testing its Galaxy home mini, which includes features with IR remocon control. When the device is added and linked to the home adjuster, the entire device is not connected as shown below.

It looks like the IR_OCF item is needed for Device Type.

2019-11-11 07:50:19 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 우리집 for smartthings
ValueError: 'IR_OCF' is not a valid DeviceType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/smartthings/__init__.py", line 116, in async_setup_entry
    devices = await api.devices(location_ids=[installed_app.location_id])
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 77, in devices
    return [DeviceEntity(self._service, entity) for entity in resp]
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 77, in <listcomp>
    return [DeviceEntity(self._service, entity) for entity in resp]
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/device.py", line 651, in __init__
    self.apply_data(data)
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/device.py", line 94, in apply_data
    self._type = DeviceType(data['type'])
  File "/usr/local/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/local/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'IR_OCF' is not a valid DeviceType

In addition, IR_OCF can not be used even after adding a device type.
Because there is no type, there is a problem that cannot be connected entirely.
If the device's property does not have a type, Exception processing is required.

2019-11-11 22:04:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 우리집 for smartthings
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 190, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/smartthings/__init__.py", line 116, in async_setup_entry
    devices = await api.devices(location_ids=[installed_app.location_id])
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 77, in devices
    return [DeviceEntity(self._service, entity) for entity in resp]
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/smartthings.py", line 77, in <listcomp>
    return [DeviceEntity(self._service, entity) for entity in resp]
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/device.py", line 651, in __init__
    self.apply_data(data)
  File "/usr/local/lib/python3.7/site-packages/pysmartthings/device.py", line 94, in apply_data
    self._type = DeviceType(data['type'])
KeyError: 'type'

**Comment by andrewsayre** [comment]
This has since been resolved.  `device_type` is now a string.
