### ISSUE TITLE
Complete example?

### ISSUE THREAD

**Issue by aadeocs** [andrewsayre/pysmartthings#18]
I have a working SmartThings (new version, not classic) hub setup working.
I have tried several variants of software using pysmartthings (0.6.9)
> https://pypi.org/project/pysmartthings/
And clues from this page.  All cases complete without printing anything.  Not sure if the problem is my token, python, hub setup, etc.

Would it be possible post a single file that has the two async function (for location) structure correct, and needing the proper token.  That would be helpful to rule out where my software is failing.

Thanks,
Dave

**Comment by posborne** [comment]
@aadeocs Posted one here: https://github.com/andrewsayre/pysmartthings/issues/20#issuecomment-571238904

**Comment by aadeocs** [comment]
posborne - thanks for the post.  That #20 post works.  Also good that that #20 has proper spacing to help get the indenting correct.

 I needed to comment this line in "def main():"
    #loop.close()
else I would get this runtime error:
----- start snippet
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x02F7BF58>
Traceback (most recent call last):
  File "C:\Users\beagles\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\beagles\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\beagles\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Users\beagles\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
----- end snippet

Program runs correctly either way.  That gets me traction to start developing!

**Comment by aadeocs** [comment]
Thanks, again
