### ISSUE TITLE
error 409 conflict when doing any capabilities.

### ISSUE THREAD

**Issue by hitime1234** [andrewsayre/pysmartthings#42]
['switch', 'audioVolume', 'audioMute', 'tvChannel', 'mediaInputSource', 'mediaPlayback', 'custom.picturemode', 'custom.error', 'custom.soundmode', 'custom.accessibility', 'custom.launchapp', 'custom.recording', 'custom.tvsearch', 'samsungtv.firmwareVersion', 'samsungtv.supportsPowerOnByOcf', 'refresh', 'execute', 'ocf', 'mediaTrackControl']
Traceback (most recent call last):
  File "C:\Users\matth\OneDrive\Desktop\samsung api.py", line 32, in <module>
    main()
  File "C:\Users\matth\OneDrive\Desktop\samsung api.py", line 30, in main
    loop.run_until_complete(locations(token))
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\matth\OneDrive\Desktop\samsung api.py", line 21, in locations
    await device.switch_on()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pysmartthings\device.py", line 990, in switch_on
    result = await self.command(component_id, Capability.switch, Command.on)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pysmartthings\device.py", line 794, in command
    self._device_id, component_id, capability, command, args
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pysmartthings\api.py", line 147, in post_device_command
    return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pysmartthings\api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\pysmartthings\api.py", line 376, in request
    resp.raise_for_status()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 946, in raise_for_status
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url=URL('https://api.smartthings.com/v1/devices/0b722b22-8cd5-4028-b407-1b397bb24b9d/commands')

**Comment by hitime1234** [comment]
I found the issue.
The tv was not connecting samsung smart things for some reason.
restarting the device made it work.
