### ISSUE TITLE
Client Response Error When Controlling Color on a Bulb

### ISSUE THREAD

**Issue by LightSlashM** [andrewsayre/pysmartthings#53]
I have been working on a piece of code that will set my lights to a certain color when I run it, and even though this code fully dose work, I get a ton of errors after I run it. Any ideas where the errors are coming from?

> import aiohttp
> import pysmartthings
> import asyncio
> 
> token = '...'
> 
> async def turn_blue():
>     async with aiohttp.ClientSession() as session:
>         api = pysmartthings.SmartThings(session, token)
>         devices = await api.devices()
>         device = devices[1]
>         result = await device.command("main", "colorControl", "setColor", [{"hue": 50, "saturation": 100}])
>         #result = await device.command("main", "colorControl", "setHue", 50)
>         assert result == True
> 
> def main():
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
>     asyncio.run(turn_blue())
> 
> if __name__ == '__main__':
>     main()

(Yes, I know the way I call a certain device is finicky but it's sad to say but it's the way I found easiest)

Here are the errors I receive:
> Traceback (most recent call last):
  File "C:\Users\jones\Desktop\Smart Thing\help.py", line 22, in <module>
    main()
  File "C:\Users\jones\Desktop\Smart Thing\help.py", line 19, in main
    asyncio.run(turn_blue())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\jones\Desktop\Smart Thing\help.py", line 13, in turn_blue
    result = await device.command("main", "colorControl", "setColor", [{"hue": 50, "saturation": 100}])
  File "C:\Users\jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pysmartthings\device.py", line 825, in command
    response = await self._api.post_device_command(
  File "C:\Users\jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pysmartthings\api.py", line 147, in post_device_command
    return await self.post(API_DEVICE_COMMAND.format(device_id=device_id), data)
  File "C:\Users\jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pysmartthings\api.py", line 395, in post
    return await self.request("post", self._api_base + resource, data=data)
  File "C:\Users\jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pysmartthings\api.py", line 376, in request
    resp.raise_for_status()
  File "C:\Users\jones\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 424, message='Failed Dependency', url=URL('https://api.smartthings.com/v1/devices/[MY-TOKEN-GOES-HERE]/commands')

**Comment by andrewsayre** [comment]
This error is coming back from the SmartThings API: `424, message='Failed Dependency'`. It's not an issue with the library (which just wraps the APIs). I suspect there's an issue with the device or device handler.
